M48
; DRILL file {KiCad 9.0.1} date 2026-02-25T19:20:26+0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-25T19:20:26+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.300
%
G90
G05
T1
X73.88Y-60.11
X73.88Y-65.89
T2
X104.95Y-80.75
T3
X97.45Y-80.75
M30
